apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: models

resources:
  - details.yaml
  - pvc.yaml
  - inferenceservice.yaml

configMapGenerator:
  - name: chgnet-server
    files:
      - server.py
    options:
      disableNameSuffixHash: true
