apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mistral-small-4-119b-2603
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-models
  resources:
    requests:
      storage: 200Gi
