apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyllama-1-1b-models
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-models
  resources:
    requests:
      storage: 5Gi
