apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bge-reranker-v2-m3-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-models
  resources:
    requests:
      storage: 5Gi
