apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esmfold-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      # Weights ~9Gi; subPath `pysite` holds pip packages
      storage: 25Gi
