apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pangu-weather
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-models
  resources:
    requests:
      storage: 30Gi
