apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: alchemi-bgr
  namespace: models
  annotations:
    autoscaling.knative.dev/scale-down-delay: "5m"
    autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    serving.knative.dev/progress-deadline-seconds: "1200"
spec:
  predictor:
    minReplicas: 0
    nodeSelector:
      gpu: "on"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
    containers:
    - name: kserve-container
      image: nvcr.io/nim/nvidia/alchemi-bgr:1.0.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8000
        protocol: TCP
      env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            name: ngc-api-key
            key: NGC_API_KEY
      - name: HOME
        value: /opt/nim/.cache
      - name: XDG_CACHE_HOME
        value: /opt/nim/.cache
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
          nvidia.com/gpumem: "40960"
        limits:
          cpu: "8"
          memory: "32Gi"
          nvidia.com/gpu: "1"
          nvidia.com/gpumem: "40960"
      readinessProbe:
        httpGet:
          path: /v1/health/ready
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 60
      startupProbe:
        httpGet:
          path: /v1/health/ready
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 120
      volumeMounts:
      - name: alchemi-bgr
        mountPath: /opt/nim/.cache
      - name: shm
        mountPath: /dev/shm
      securityContext:
        runAsUser: 0
    imagePullSecrets:
    - name: ngc-registry-secret
    volumes:
    - name: alchemi-bgr
      persistentVolumeClaim:
        claimName: alchemi-bgr
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
