apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clap-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
