apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphcast-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-models
  resources:
    requests:
      storage: 20Gi
