apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: granite-geospatial-ocean-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-models
