apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kandinsky-3-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-models
  resources:
    requests:
      storage: 50Gi
