apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mace-mp-0-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
