apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: depth-anything-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-models
  resources:
    requests:
      storage: 5Gi
