apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mast3r-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
