apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolov8s-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
