apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fourcastnet3-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
