apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oceangpt-30b-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      # 61 GB weights + headroom
      storage: 80Gi
