apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timer-s1-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-models
  resources:
    requests:
      storage: 25Gi
