apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mace-mh-1
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-models
