apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-120b
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Gi
