apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moirai-moe-1-0-r-base-data
  namespace: models
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
