apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moirai-moe-1-0-r-base
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-models
  resources:
    requests:
      storage: 5Gi
