apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phi-4-reasoning-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      # 14B model ~28GB
      storage: 40Gi
