apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surya-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
