apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sam3-1
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-models
  resources:
    requests:
      storage: 40Gi
