apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-vl-3b-data
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-models
  resources:
    requests:
      storage: 20Gi
