apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-v2-lite-16b
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 40Gi
