apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kandinsky-3-1-flash
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-models
  resources:
    requests:
      storage: 100Gi
