apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astropt-data
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
