apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: colabfold-msa-search
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-models
  resources:
    requests:
      storage: 50Gi
