apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aya-expanse-8b
  namespace: models
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-models
  resources:
    requests:
      storage: 25Gi
